name: GitHub Projects Automation
on:
  pull_request:
    types: [closed]
jobs:
  move-issue-to-done:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Simulate Issue Movement"